In [2]:
import pandas as pd
import tensorflow as tf

In [3]:
iris_csv = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv'
iris = pd.read_csv(iris_csv)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [12]:
# Onehot-encoding
print(iris.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [13]:
iris['품종'] = iris['품종'].astype('category')
print(iris.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [15]:
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

In [17]:
encoding.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종_0     0
품종_1     0
품종_2     0
dtype: int64

In [20]:
encoding.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
145   6.7  3.000000    5.2   2.3     0     0     1
146   6.3  2.500000    5.0   1.9     0     0     1
147   6.5  3.000000    5.2   2.0     0     0     1
148   6.2  3.400000    5.4   2.3     0     0     1
149   5.9  3.054362    5.1   1.8     0     0     1

In [23]:
# NA 값에 꽃잎폭 평균 값을 넣어준다.
mean = encoding['꽃잎폭'].mean()
encoding['꽃잎폭'] = encoding['꽃잎폭'].fillna(mean)
encoding.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
145   6.7  3.000000    5.2   2.3     0     0     1
146   6.3  2.500000    5.0   1.9     0     0     1
147   6.5  3.000000    5.2   2.0     0     0     1
148   6.2  3.400000    5.4   2.3     0     0     1
149   5.9  3.054362    5.1   1.8     0     0     1

In [24]:
print(encoding.columns)
x = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y = encoding[['품종_0', '품종_1', '품종_2']]

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_0', '품종_1', '품종_2'], dtype='object')


In [44]:
# build a model
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(5, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
             metrics='accuracy')
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 18        
Total params: 103
Trainable params: 103
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 606us/step - loss: 0.0506 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 598us/step - loss: 0.0452 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 791us/step - loss: 0.0463 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0481 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 798us/step - loss: 0.0468 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 603us/step - loss: 0.0476 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0440 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 594us/step - loss: 0.0485 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 798us/step - loss: 0.0469 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 992us/step - loss: 0.0441 - accuracy: 0.9800


In [39]:
model.predict(x[0:5])

array([[1.0000000e+00, 1.2307834e-08, 9.1413768e-14],
       [1.0000000e+00, 1.2295539e-08, 8.6231125e-14],
       [1.0000000e+00, 9.1038164e-09, 5.4793863e-14],
       [1.0000000e+00, 8.4762268e-09, 4.5447285e-14],
       [1.0000000e+00, 1.5744481e-08, 1.0511911e-13]], dtype=float32)

In [40]:
print(y[0:5])

   품종_0  품종_1  품종_2
0     1     0     0
1     1     0     0
2     1     0     0
3     1     0     0
4     1     0     0


In [41]:
model.predict(x[-6:-1])

array([[1.71895445e-05, 2.26299721e-03, 9.97719824e-01],
       [3.23540298e-05, 3.42167611e-03, 9.96545970e-01],
       [1.03282517e-04, 1.12095615e-02, 9.88687158e-01],
       [7.58241804e-05, 1.49434535e-02, 9.84980702e-01],
       [3.29558461e-05, 3.10237636e-03, 9.96864617e-01]], dtype=float32)

In [42]:
print(y[-6:-1])

     품종_0  품종_1  품종_2
144     0     0     1
145     0     0     1
146     0     0     1
147     0     0     1
148     0     0     1


In [43]:
model.get_weights()

[array([[ 0.6755006 ,  0.00535846, -0.18528229,  0.43668646,  0.18438812],
        [ 0.5425636 ,  0.08755983,  1.064205  , -0.18922281, -0.1117766 ],
        [-0.6402648 , -0.4229297 , -0.5022555 ,  0.3397778 , -0.8450607 ],
        [-0.89725935, -0.72044253, -1.489894  ,  1.0151193 , -0.19090003]],
       dtype=float32),
 array([ 0.28151947,  0.6327271 ,  0.47574604, -0.3135926 ,  0.29148468],
       dtype=float32),
 array([[ 0.1266336 ,  0.07932285, -1.0724405 , -0.43457833,  0.04595942],
        [-0.12185576, -0.53553474,  1.192123  , -1.0502815 ,  0.02795548],
        [-0.5646591 , -1.1534551 ,  0.38142362,  0.2679518 , -1.8030653 ],
        [-0.52850485, -0.06840092,  0.76699954, -0.3987854 ,  0.83486944],
        [-0.08273188,  0.22736341,  0.73012596, -0.19545028,  0.15346617]],
       dtype=float32),
 array([ 0.33683842,  0.5162077 , -0.30923712,  0.35247767,  0.34782392],
       dtype=float32),
 array([[ 0.00393922, -1.4757864 , -1.0100495 , -0.9781309 , -0.5607791 ],
        