In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
iris_csv = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(iris_csv)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# Onehot-encoding
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# seperate x and y
print(encoding.columns)
x = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(x.shape, y.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 4) (150, 3)


In [5]:
# build a model
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
             metrics='accuracy')

In [6]:
model.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 798us/step - loss: 0.1686 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 598us/step - loss: 0.1683 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 598us/step - loss: 0.1682 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 696us/step - loss: 0.1682 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 598us/step - loss: 0.1679 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 599us/step - loss: 0.1680 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 797us/step - loss: 0.1678 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1675 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 599us/step - loss: 0.1673 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 605us/step - loss: 0.1678 - accuracy: 0.9800


In [7]:
model.predict(x[0:5])

array([[9.9884534e-01, 1.1545769e-03, 7.4857461e-08],
       [9.9647826e-01, 3.5211183e-03, 6.4470066e-07],
       [9.9793482e-01, 2.0649035e-03, 2.5356766e-07],
       [9.9524117e-01, 4.7577908e-03, 1.0296231e-06],
       [9.9898058e-01, 1.0193703e-03, 5.8650933e-08]], dtype=float32)

In [8]:
print(y[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
model.predict(x[-6:-1])

array([[5.2215938e-08, 8.3169244e-02, 9.1683066e-01],
       [5.4039253e-07, 1.6224036e-01, 8.3775914e-01],
       [1.6207267e-06, 1.8555216e-01, 8.1444621e-01],
       [2.6569305e-06, 2.6628214e-01, 7.3371518e-01],
       [5.0605462e-07, 1.7536017e-01, 8.2463932e-01]], dtype=float32)

In [10]:
print(y[-6:-1])

     품종_setosa  품종_versicolor  품종_virginica
144          0              0             1
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1


In [11]:
model.get_weights()

[array([[ 0.6652158 , -0.04049774, -0.6704833 ],
        [ 2.4419453 ,  0.48939502, -1.3349226 ],
        [-2.715384  ,  0.14249854,  1.7484299 ],
        [-4.6293035 , -0.5016495 ,  2.0119648 ]], dtype=float32),
 array([ 2.164861 ,  1.0084928, -1.7881553], dtype=float32)]